minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - js-yaml@4.1.2
  - '@babel/core@7.29.1'
overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@<=4.1.1: ^4.1.2
  minimatch@<10.2.1: '>=10.2.1'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
