[versions]
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
jackson = "2.19.2"
log4j = "2.25.1"
sqlite = "3.49.1.0"
flyway = "11.4.0"
openai = "3.0.2"
anthropic = "0.8.0"
shadow = "9.2.2"
protobuf = "4.33.4"
kotlinpoet = "2.2.0"
diff-utils = "4.15"
jgit = "7.2.0.202503040940-r"
ktreesitter = "0.24.1"
tree-sitter-java = "0.24.5"
tree-sitter-ts = "0.21.1"
graalvm = "24.1.2"

[libraries]
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
openai = { group = "com.openai", name = "openai-java", version.ref = "openai" }
anthropic = { group = "com.anthropic", name = "anthropic-java", version.ref = "anthropic" }
protobuf = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
diffutils = { group = "io.github.java-diff-utils", name = "java-diff-utils", version.ref = "diff-utils" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
ktreesitter = { group = "io.github.tree-sitter", name = "ktreesitter", version.ref = "ktreesitter" }
treesitter-java = { group = "io.github.bonede", name = "tree-sitter", version.ref = "tree-sitter-java" }
treesitter-ts = { group = "io.github.bonede", name = "tree-sitter-typescript", version.ref = "tree-sitter-ts" }
graalvm-js = { group = "org.graalvm.polyglot", name = "js", version.ref = "graalvm" }
graalvm-polyglot = { group = "org.graalvm.polyglot", name = "polyglot", version.ref = "graalvm" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }