// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: schema.proto
#ifndef GRPC_schema_2eproto__INCLUDED
#define GRPC_schema_2eproto__INCLUDED

#include "schema.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace hellostreaming {

class HelloService final {
 public:
  static constexpr char const* service_full_name() {
    return "hellostreaming.HelloService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::hellostreaming::HelloResponse>> SayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::hellostreaming::HelloResponse>>(SayHelloRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>> AsyncSayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>>(AsyncSayHelloRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest* request, ::grpc::ClientReadReactor< ::hellostreaming::HelloResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::hellostreaming::HelloResponse>* SayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::hellostreaming::HelloResponse>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::hellostreaming::HelloResponse>> SayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::hellostreaming::HelloResponse>>(SayHelloRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>> AsyncSayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>>(AsyncSayHelloRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest* request, ::grpc::ClientReadReactor< ::hellostreaming::HelloResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::hellostreaming::HelloResponse>* SayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request) override;
    ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::hellostreaming::HelloRequest* request, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::hellostreaming::HelloRequest* request, ::grpc::ServerAsyncWriter< ::hellostreaming::HelloResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::hellostreaming::HelloRequest, ::hellostreaming::HelloResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hellostreaming::HelloRequest* request) { return this->SayHello(context, request); }));
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::hellostreaming::HelloResponse>* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SayHello(context, request); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::hellostreaming::HelloRequest, ::hellostreaming::HelloResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::hellostreaming::HelloRequest, ::hellostreaming::HelloResponse>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hellostreaming::HelloRequest* /*request*/, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::hellostreaming::HelloRequest,::hellostreaming::HelloResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SayHello<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_SayHello<Service > StreamedService;
};

}  // namespace hellostreaming


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_schema_2eproto__INCLUDED
