// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: schema.proto

#include "schema.pb.h"
#include "schema.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hellostreaming {

static const char* HelloService_method_names[] = {
  "/hellostreaming.HelloService/SayHello",
};

std::unique_ptr< HelloService::Stub> HelloService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HelloService::Stub> stub(new HelloService::Stub(channel, options));
  return stub;
}

HelloService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(HelloService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::hellostreaming::HelloResponse>* HelloService::Stub::SayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hellostreaming::HelloResponse>::Create(channel_.get(), rpcmethod_SayHello_, context, request);
}

void HelloService::Stub::async::SayHello(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest* request, ::grpc::ClientReadReactor< ::hellostreaming::HelloResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hellostreaming::HelloResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>* HelloService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hellostreaming::HelloResponse>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hellostreaming::HelloResponse>* HelloService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hellostreaming::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hellostreaming::HelloResponse>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false, nullptr);
}

HelloService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< HelloService::Service, ::hellostreaming::HelloRequest, ::hellostreaming::HelloResponse>(
          [](HelloService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hellostreaming::HelloRequest* req,
             ::grpc::ServerWriter<::hellostreaming::HelloResponse>* writer) {
               return service->SayHello(ctx, req, writer);
             }, this)));
}

HelloService::Service::~Service() {
}

::grpc::Status HelloService::Service::SayHello(::grpc::ServerContext* context, const ::hellostreaming::HelloRequest* request, ::grpc::ServerWriter< ::hellostreaming::HelloResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hellostreaming

